---
title: "William Pearman <br> Curriculum vitae"
output:
  pagedown::html_paged:
    css: ["css/bootstrap-5.2.1.min.css", "css/two-col-cv.css"]
    number_sections: false
knit: pagedown::chrome_print
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(dplyr)
library(glue)
library(fontawesome)
library(knitr)
source("_common.R")
meta <- load_meta()
view <- "full_cv"

# Hidden-header, 2-column (year | description) table, matching the
# pagedownCV visual style -- CSS hides <thead> and sizes the year column.
year_table <- function(d, year_col, text_col) {
  d |>
    transmute(Year = .data[[year_col]], What = .data[[text_col]]) |>
    kable(col.names = c("", ""), escape = FALSE)
}
```

::: {.row}

:::::: {.col-7 .summary}

# Research summary

`r meta$speciality`

::::::

:::::: {.col-5}

# Contact {.box}

::::::::: {.info-box}

| Center | Left |
|:------:|:-----|
| `r fa("map-marker-alt")` | `r meta$employer`, `r positions_tibble()$location[1]` |
| `r fa("envelope")` | `r meta$email` |
| `r fa("orcid")` | [`r meta$orcid`](`r meta$orcid_url`) |
| `r fa("github")` | [`r url_handle(meta$github)`](`r meta$github`) |

:::::::::

::::::

:::

::: {.row}

:::::: {.col-6 .left}

# Education

```{r}
cv_entries("education", view) |>
  mutate(what = glue("<span class='cv-entry-title'>{title}</span>, {where}, {location}")) |>
  year_table("year", "what")
```

::::::

:::::: {.col-6 .right}

# Selected teaching experience

```{r}
#| results: asis
cat(render_cv_section("teaching", view))
```

::::::

:::

```{r}
#| results: asis
# Balance Awards/Grants/Talks/Service/Professional development between
# the two columns by estimated content height (allocate_columns()),
# then split each column at the exact point that fits on the rest of
# page 1 (split_column()) -- see the long comment above those
# functions in _common.R for why this is computed manually rather than
# left to the browser.
col_alloc <- allocate_columns(c("award", "grant", "talk", "service", "prof-dev"), view)
left_blocks  <- column_blocks(col_alloc$left, view)
right_blocks <- column_blocks(col_alloc$right, view)
page1_budget <- CV_PAGE_BOTTOM_PT - CV_BALANCED_BLOCK_START_PT
left_split  <- split_column(left_blocks, page1_budget)
right_split <- split_column(right_blocks, page1_budget)
cat(render_balanced_block(left_split$page1, right_split$page1))
cat(render_balanced_block(left_split$rest, right_split$rest))
```

::: {.row}

:::::: {.col-12}

# Publications

```{r}
#| results: asis
cat(render_cv_publications(view))
```

::::::

:::
