project:
  type: website
  output-dir: docs

website:
  title: "William Pearman"
  description: "Personal website of William Pearman, molecular and microbial ecologist"
  site-url: https://wpearman1996.github.io/
  favicon: favicon.png
  page-navigation: true
  search:
    location: navbar
    type: overlay
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - text: "Research"
        href: research.qmd
      - text: "Metrics"
        href: metrics.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Talks"
        href: talks/index.qmd
      - text: "CV"
        href: cv.qmd

  page-footer:
    center: "<a href='cv.pdf'>CV</a> &nbsp;<a href='https://github.com/wpearman1996' target='_blank'><i class='bi bi-github'></i></a> &nbsp;<a href='https://www.linkedin.com/in/william-pearman-6b3188392/' target='_blank'><i class='bi bi-linkedin'></i></a> &nbsp;<a href='https://bsky.app/profile/williampearman.bsky.social' target='_blank'><i class='fa-brands fa-bluesky'></i></a> &nbsp;<a href='https://scholar.google.co.nz/citations?user=Gn6BJkoAAAAJ&hl=en' target='_blank'><i class='ai ai-google-scholar fa-lg'></i></a><br>Site made with <i class='bi bi-heart-fill'></i> and <a href='https://quarto.org/' target='_blank'>Quarto</a><br>&copy; 2026 William Pearman"

format:
  html:
    theme: [default, css/theme.scss]
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: false
    include-in-header: "_includes/header.html"
    toc: true
