---
title: "About"
toc: true
toc-location: left
---

Welcome! I'm a Research Fellow at the [University of Auckland](https://www.auckland.ac.nz/), working at the intersection of population genomics and microbial ecology. See my [CV](cv.qmd) for the full record, or my [Research](research.qmd) page for publications and [citation metrics](metrics.qmd).

## Background

I did my PhD at the University of Otago, in Dunedin, New Zealand, focused on seaweed population genomics and microbiome structure. Before that, I completed a Master of Natural Science (Distinction) and Bachelor of Natural Science at Massey University, both specialising in molecular ecology. I now work as a Research Fellow at the University of Auckland, having previously been an Assistant Research Fellow and Lab Manager at the University of Otago.

## Research

I am a broadly trained molecular and microbial ecologist with principal expertise in population genomics and microbial ecology. I specialise in developing eco-evolutionary simulations of microbial communities to develop hypotheses which I then test using observational data and experiments.

My research background is a combination of population genomics and microbial ecology, with my current research interests working to align these two fields to understand the evolution of host-microbe relationships. My current work combines eco-evolutionary modelling of holobiont evolution, and experimental work with *Daphnia* to determine microbial contributions to host fitness and to understand host-microbial responses to environmental perturbations. In addition to these areas, I am also actively involved in the application and optimisation of new molecular biology protocols for non-model organisms.

More than anything, I like solving problems. Most of my work to date has been focussed on interesting questions, or tricky problems - like why some species don't sequence so well with nanopore sequencing.

## Get in Touch

Feel free to get in touch if you want a copy of any of my publications, or if you're interested in collaborating.
